import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("use-document-title", "routes/use-document-title.tsx"),
  route("use-default", "routes/use-default.tsx"),
  route("use-toggle", "routes/use-toggle.tsx"),
  route("use-previous", "routes/use-previous.tsx"),
  route("use-preferred-language", "routes/use-preferred-language.tsx"),
  route("use-favicon", "routes/use-favicon.tsx"),
  route("use-copy-to-clipboard", "routes/use-copy-to-clipboard.tsx"),
  route("use-interval", "routes/use-interval.tsx"),
  route("use-counter", "routes/use-counter.tsx"),
  route("use-lock-body-scroll", "routes/use-lock-body-scroll.tsx"),
  route("use-queue", "routes/use-queue.tsx"),
  route("use-timeout", "routes/use-timeout.tsx"),
  route("use-window-size", "routes/use-window-size.tsx"),
  route("use-visibility-change", "routes/use-visibility-change.tsx"),
  route("use-list", "routes/use-list.tsx"),
  route("use-object-state", "routes/use-object-state.tsx"),
  route("use-debounce", "routes/use-debounce.tsx"),
  route("use-continuous-retry", "routes/use-continuous-retry.tsx"),
  route("use-history-state", "routes/use-history-state.tsx"),
  route("use-random-interval", "routes/use-random-interval.tsx"),
  route("use-media-query", "routes/use-media-query.tsx"),
  route("use-mouse", "routes/use-mouse.tsx"),
] satisfies RouteConfig;
